/// Risc0 zkVM prover for UTXO payment batches.
///
/// `Prover::prove_batch` runs the `kryptis-guest` program inside the Risc0
/// zkVM and returns a cryptographic receipt.  In development mode
/// (`RISC0_DEV_MODE=1`) a mock receipt is returned instantly — no RISC-V
/// toolchain or real proving is required.
///
/// `Prover::verify` decodes the receipt's journal and confirms that the
/// committed `new_state_root` matches the host's expectation.
///
/// # Snapshot ordering
/// `prove_batch` takes `pre_batch_snapshots` — the UTXOs **before** the
/// batch was applied.  Callers must capture `utxo_set.to_snapshots()` before
/// calling `ExecutionDomain::produce_batch`, then pass the saved snapshots to
/// this function.  This ensures the guest can verify the old state root.
use kryptis_types::{BatchInput, BatchOutput, SerializablePayment, SerializableUtxo};
use risc0_zkvm::{ExecutorEnv, Receipt};

use crate::{
    core::error::{KryptisError, KryptisResult},
    execution::batch::PaymentBatch,
};

// Generated by build.rs / risc0-build::embed_methods().
// In RISC0_DEV_MODE=1 + RISC0_SKIP_BUILD=1 these are empty/zeroed stubs
// that still compile; the mock prover does not need real ELF bytes.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// Converts a hex string to a 32-byte array.
///
/// Panics if the string is not exactly 64 hex chars — callers must guarantee
/// that all Hash values produced by the execution domain are valid.
pub(crate) fn hex_to_bytes32(hex: &str) -> [u8; 32] {
    let bytes = hex::decode(hex).expect("invalid hex hash");
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    arr
}

/// Builds a `SerializablePayment` from the host `Payment` type.
fn to_serializable_payment(p: &crate::execution::utxo::Payment) -> SerializablePayment {
    SerializablePayment {
        inputs: p.inputs.iter().map(|id| hex_to_bytes32(id)).collect(),
        outputs: p.outputs.iter().map(|o| (o.owner.clone(), o.amount)).collect(),
        fee: p.fee,
        signature: p.signature.clone(),
        public_key: p.public_key.clone(),
    }
}

/// ZK batch prover wrapping the Risc0 proving system.
pub struct Prover;

impl Prover {
    /// Prove that `batch` is a valid state transition given the UTXO set
    /// **before** the batch was applied (`pre_batch_snapshots`).
    ///
    /// Returns a `Receipt` whose journal encodes a `BatchOutput`.
    /// In dev mode this completes in milliseconds (mock prover).
    pub fn prove_batch(
        batch: &PaymentBatch,
        pre_batch_snapshots: Vec<SerializableUtxo>,
    ) -> KryptisResult<Receipt> {
        let input = BatchInput {
            old_state_root: hex_to_bytes32(&batch.old_state_root),
            payments: batch.payments.iter().map(to_serializable_payment).collect(),
            utxo_snapshots: pre_batch_snapshots,
        };

        let env = ExecutorEnv::builder()
            .write(&input)
            .map_err(|e| KryptisError::ProofGenerationFailed(e.to_string()))?
            .build()
            .map_err(|e| KryptisError::ProofGenerationFailed(e.to_string()))?;

        let receipt = risc0_zkvm::default_prover()
            .prove(env, KRYPTIS_GUEST_ELF)
            .map_err(|e| KryptisError::ProofGenerationFailed(e.to_string()))?
            .receipt;

        Ok(receipt)
    }

    /// Verify `receipt` and confirm the committed new state root matches
    /// `expected_new_root` (hex string from the execution domain).
    pub fn verify(receipt: &Receipt, expected_new_root: &str) -> KryptisResult<BatchOutput> {
        receipt
            .verify(KRYPTIS_GUEST_ID)
            .map_err(|e| KryptisError::ProofVerificationFailed(e.to_string()))?;

        let output: BatchOutput = receipt
            .journal
            .decode()
            .map_err(|e| KryptisError::ProofVerificationFailed(e.to_string()))?;

        if hex::encode(output.new_state_root) != expected_new_root {
            return Err(KryptisError::StateMismatch);
        }

        Ok(output)
    }
}
